// frontend/src/components/ticketView/TicketStatusBar.vue
<template>
    <div class="ticket-status-bar" v-if="ticket">
        <StatusSelector :status="ticket.status" class="mr-3" @Change-status="selectStatus"/>
        <hr style="rotate: 90deg;width: 1.5em"/>
        <PrioritySelector
            class="ml-3"
            :current-priority="ticket.priority"
            @selectPriority="selectPriority"/>
        <i class="fa-solid fa-trash" @click="deleteTicket" role="button"/>
    </div>
</template>

<script lang="ts">
import type {Priority} from "@/enum/priority";
import type {PropType} from "vue";
import {defineComponent} from "vue";
import PrioritySelector from "@/components/PrioritySelector.vue";
import StatusSelector from "@/components/ticketView/StatusSelector.vue";
import type {TicketDetails} from "@/model/ticketDetails";
import TicketService from "@/services/ticketService";
import type {TicketStatus} from "@/enum/ticketStatus";

export default defineComponent({
    name: "TicketStatusBar",
    components: {StatusSelector, PrioritySelector},
    props: {
        ticket: {
            type: Object as PropType<TicketDetails>,
            required: true
        }
    },
    emits: ["selectPriority", "CloseTicketView"],
    methods: {
        selectPriority(priority: Priority) {
            TicketService.updatePriority(this.ticket.id, priority, this.ticket);
        },
        selectStatus(status: TicketStatus) {
            TicketService.updateStatus(this.ticket.id, status, this.ticket);
        },
        deleteTicket() {
            TicketService.deleteTicket(this.ticket.id);
            this.$emit("CloseTicketView");
        }
    }
});
</script>

<style scoped lang="less">
.ticket-status-bar {
    width: 100%;
    padding: 20px;
    height: 80px;
    border-bottom: 1px solid var(--navigation-border-color);
    display: flex;
    align-items: center;
}
</style>

// frontend-react/src/components/ticketView/ticketMainColumn/ticketStatusBar/ticketStatusBar.tsx
import "./ticketStatusBar.less";
import StatusSelector from "./statusSelector/statusSelector.tsx";
import {TicketDetails} from "../../../../model/ticketDetails.ts";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faTrash} from "@fortawesome/free-solid-svg-icons/faTrash";
import {Priority} from "../../../../enum/priority.ts";
import {TicketStatus} from "../../../../enum/ticketStatus.ts";
import PrioritySelector from "../../../prioritySelector/prioritySelector.tsx";
import TicketServices from "../../../../services/ticketServices.ts";

interface TicketStatusBarProps {
    ticket: TicketDetails;
    OnTicketViewClosed: () => void;
}

function TicketStatusBar(props: TicketStatusBarProps) {
    const selectPriority = (priority: Priority) => {
        //TicketServices.updatePriority(props.ticket.id, priority, props.ticket);
    }

    const selectStatus = (status: TicketStatus) => {
        //TicketServices.updateStatus(props.ticket.id, status, props.ticket);
    }

    const deleteTicket = () => {
        props.OnTicketViewClosed();
        TicketServices.deleteTicket(props.ticket.id);
    }

    return props.ticket && <div className="ticket-status-bar">
        <div className="mr-3">
            <StatusSelector status={props.ticket.status} changeStatus={selectStatus}/>
        </div>

        <hr style={{rotate: "90deg", width: "1.5em", margin: 0}}/>
        <div className="ml-3">
            <PrioritySelector currentPriority={props.ticket.priority} selectPriority={selectPriority}/>
        </div>

        <FontAwesomeIcon icon={faTrash} className="fa-solid fa-trash" onClick={deleteTicket}/>
    </div>;
}

export default TicketStatusBar;
