// frontend-react/src/components/ticketView/ticketMainColumn/ticketStatusBar/statusSelector/statusSelector.tsx
import "./statusSelector.less"
import React from 'react'
import BackgroundBlocker from "../../../../utils/BackgroundBlocker.tsx";
import {TicketStatus} from "../../../../../enum/ticketStatus.ts";

interface StatusSelectorProps {
    status: TicketStatus;
    changeStatus: (status: TicketStatus) => void;
    className?: string;
}

interface StatusSelectorState {
    selectorOpened: boolean
}

class StatusSelector extends React.Component<StatusSelectorProps, StatusSelectorState> {
    constructor(props: StatusSelectorProps) {
        super(props);
        this.state  = {
            selectorOpened: false
        }
    }

    toggleSelector() {
        this.setState(prevState => ({selectorOpened: !prevState.selectorOpened}))
    }
    currentStatus() {
        switch (this.props.status) {
            case TicketStatus.IN_PROGRESS:
                return "In Bearbeitung";
            case TicketStatus.BACKLOG:
                return "Backlog";
            case TicketStatus.PLANNED:
                return "In Planung";
            case TicketStatus.TO_REVIEW:
                return "Im Review";
            case TicketStatus.DONE:
                return "Abgeschlossen";
            default:
                return "Ungültiger Status";
        }
    }
    setNewStatus(status: TicketStatus) {
        this.props.changeStatus(status);
        this.setState({selectorOpened: false});
    }
    render() {

        return <div className={`status-selector-container ${this.props.className}`} >
                <button className="status-selector-main"  style={{zIndex: this.state.selectorOpened ? "60" : ""}} onClick={this.toggleSelector.bind(this)}>
                    <span className="user-select-none">{this.currentStatus()}</span>
                    <i className="fa-solid fa-caret-right ml-1" style={{rotate: this.state.selectorOpened ? "90deg" : ""}}/>
                </button>
                {this.state.selectorOpened && <div className="status-selector-overlay">
                    {this.props.status != TicketStatus.BACKLOG  && <span className="status-selector-item" onClick={() => this.setNewStatus(TicketStatus.BACKLOG)}>Backlog</span>}
                    {this.props.status != TicketStatus.PLANNED  && <span className="status-selector-item" onClick={() => this.setNewStatus(TicketStatus.PLANNED)}>Geplant</span>}
                    {this.props.status != TicketStatus.IN_PROGRESS &&  <span className="status-selector-item" onClick={() => this.setNewStatus(TicketStatus.IN_PROGRESS)}>In Arbeit</span>}
                    {this.props.status != TicketStatus.TO_REVIEW && <span className="status-selector-item" onClick={() => this.setNewStatus(TicketStatus.TO_REVIEW)}>Im Review</span>}
                    {this.props.status != TicketStatus.DONE  && <span className="status-selector-item" onClick={() => this.setNewStatus(TicketStatus.DONE)}>Abgeschlossen</span>}
                </div>}
                { this.state.selectorOpened && <BackgroundBlocker onClick={this.toggleSelector.bind(this)}/>}
            </div>;
    }

}

export default StatusSelector;

// frontend/src/components/ticketView/StatusSelector.vue
<template>
    <div class="status-selector-container">
        <div class="status-selector-main" :style="zIndexStyle" role="button" @click="toggleSelector">
            <span class="user-select-none">{{ currentStatus }}</span>
            <i class="fa-solid fa-caret-right ml-1" :style="selectorIconStyle"/>
        </div>
        <div class="status-selector-overlay" v-if="selectorOpened">
            <span class="status-selector-item" v-if="status != TicketStatus.BACKLOG" @click="setNewStatus(TicketStatus.BACKLOG)">Backlog</span>
            <span class="status-selector-item" v-if="status != TicketStatus.PLANNED" @click="setNewStatus(TicketStatus.PLANNED)">Geplant</span>
            <span class="status-selector-item" v-if="status != TicketStatus.IN_PROGRESS"
                  @click="setNewStatus(TicketStatus.IN_PROGRESS)">In Arbeit</span>
            <span class="status-selector-item" v-if="status != TicketStatus.TO_REVIEW" @click="setNewStatus(TicketStatus.TO_REVIEW)">Im Review</span>
            <span class="status-selector-item" v-if="status != TicketStatus.DONE" @click="setNewStatus(TicketStatus.DONE)">Abgeschlossen</span>
        </div>
        <BackgroundBlocker v-if="selectorOpened" @click="toggleSelector"/>
    </div>
</template>

<script lang="ts">
import type {PropType} from "vue";
import {defineComponent} from "vue";
import {TicketStatus} from "@/enum/ticketStatus";
import BackgroundBlocker from "@/components/utils/BackgroundBlocker.vue";

export default defineComponent({
    name: "StatusSelector",
    components: {BackgroundBlocker},
    emits: ["changeStatus"],
    props: {
        status: {
            type: Number as PropType<TicketStatus>
        }
    },
    data() {
        return {
            selectorOpened: false
        }
    },
    computed: {
        TicketStatus() {
            return TicketStatus;
        },
        currentStatus() {
            switch (this.status) {
                case TicketStatus.IN_PROGRESS:
                    return "In Bearbeitung";
                case TicketStatus.BACKLOG:
                    return "Backlog";
                case TicketStatus.PLANNED:
                    return "In Planung";
                case TicketStatus.TO_REVIEW:
                    return "Im Review";
                case TicketStatus.DONE:
                    return "Abgeschlossen";
                default:
                    return "Ungültiger Status";
            }
        },
        zIndexStyle() {
            return this.selectorOpened ? "z-index: 60" : "";
        },
        selectorIconStyle() {
            return this.selectorOpened ? "rotate: 90deg" : "";
        },
    },
    methods: {
        toggleSelector() {
            this.selectorOpened = !this.selectorOpened;
        },
        setNewStatus(status: TicketStatus) {
            this.$emit("changeStatus", status);
            this.selectorOpened = false;
        }
    }
});
</script>

<style scoped lang="less">
.status-selector-container {
  position: relative;
  display: flex;
  flex-direction: column;

  .status-selector-main {
    display: flex;
    align-items: center;
    justify-content: space-between;

    border-radius: 4px;
    padding: 5px 10px;
    min-width: 150px;
    background-color: var(--status-selector-background-color);
    color: var(--status-selector-text-color);
  }

  .status-selector-overlay {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: calc(100% - 10px);
    width: 100%;
    padding: 15px 10px 5px 10px;
    user-select: none;
    z-index: 55;
    background-color: var(--main-background-color);
    border: 1px solid var(--status-selector-background-color);
    border-radius: 0 0 4px 4px;

    .status-selector-item {
      padding: 3px 5px;
      border-radius: 8px;

      &:hover {
        background-color: var(--status-selector-background-color);
        color: var(--status-selector-text-color);
        cursor: pointer;
      }
    }
  }
}
</style>
