// frontend-react/src/components/ticketView/ticketMainColumn/ticketMainColumn.tsx
import "./ticketMainColumn.less";
import TicketStatusBar from "./ticketStatusBar/ticketStatusBar.tsx";
import {TicketDetails} from "../../../model/ticketDetails.ts";
import TicketServices from "../../../services/ticketServices.ts";

interface TicketMainColumnProps {
    ticket: TicketDetails;
    onTicketViewClosed: () => void;
}

function TicketMainColumn(props: TicketMainColumnProps) {
    let title = props.ticket.title;
    let description = props.ticket.description;

    const saveNewTitle = () => {
        if (title === "") {
            title = props.ticket.title;
            return;
        }
        TicketServices.updateTitle(props.ticket.id, title, props.ticket);
    };

    const saveNewDescription = () => {
        if (description === "") {
            description = props.ticket.description;
            return;
        }
        TicketServices.updateDescription(props.ticket.id, description, props.ticket);
    }

    return <div className="main-column-container">
        <TicketStatusBar ticket={props.ticket} OnTicketViewClosed={props.onTicketViewClosed}/>

        <div className="main-column">
            <input type="text"
                   id="name-field"
                   value={title}
                   onChange={(input) => title = input.target.value}
                   className="ticket-name-input"
                   onBlur={saveNewTitle}
            />
            <textarea id="name-field"
                      value={description}
                      className="ticket-description-input"
                      onChange={(input) => description = input.target.value}
                      placeholder="Geben Sie hier eine Beschreibung ein..."
                      onBlur={saveNewDescription}
            />
        </div>
    </div>;
}

export default TicketMainColumn;

// frontend/src/components/ticketView/TicketMainColumn.vue
<template>
    <div class="main-column-container">
        <TicketStatusBar :ticket="ticket" @CloseTicketView="closeTicketView"/>
        <div class="main-column">
            <input type="text" id="name-field" v-model="newTitle" class="ticket-name-input" @focusout="saveNewTitle"/>
            <textarea type="text" id="name-field" v-model="newDescription" class="ticket-description-input"
                      placeholder="Geben Sie hier eine Beschreibung ein..." @focusout="saveNewDescription"/>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent, type PropType} from "vue";
import TicketStatusBar from "@/components/ticketView/TicketStatusBar.vue";
import type {TicketDetails} from "@/model/ticketDetails";
import TicketService from "@/services/ticketService";

export default defineComponent({
    name: "TicketMainColumn",
    components: {TicketStatusBar},
    emits: ["CloseTicketView"],
    props: {
        ticket: {
            type: Object as PropType<TicketDetails>,
            required: true
        }
    },
    data() {
        return {
            newTitle: "",
            newDescription: ""
        }
    },
    mounted() {
        this.newTitle = this.ticket.title;
        this.newDescription = this.ticket.description;
    },
    methods: {
        closeTicketView() {
            this.$emit("CloseTicketView");
        },
        saveNewTitle() {
            if (this.newTitle === "") {
                this.newTitle = this.ticket.title;
                return;
            }

            TicketService.updateTitle(this.ticket.id, this.newTitle, this.ticket);
        },
        saveNewDescription() {
            TicketService.updateDescription(this.ticket.id, this.newDescription, this.ticket);
        }
    }
});
</script>

<style scoped lang="less">
.main-column-container {
    width: 60%;
    border-right: 1px solid var(--navigation-border-color);
    display: flex;
    flex-direction: column;

    .main-column {
        display: flex;
        flex-direction: column;
        padding: 30px;
        flex-grow: 1;

        .ticket-name-input {
            padding: 11px;
            width: 100%;
            border: none;
            outline: none;
            font-size: 1.5em;
            margin-bottom: 30px;

            &:hover, &:focus {
                padding: 10px;
                border: 1px dashed var(--navigation-border-color);
            }
        }

        .ticket-description-input {
            padding: 21px;
            width: 100%;
            flex-grow: 1;
            border: none;
            outline: none;
            margin-bottom: 30px;
            resize: none;

            &:hover, &:focus {
                padding: 20px;
                border: 1px dashed var(--navigation-border-color);
            }
        }
    }
}
</style>
