// frontend-react/src/components/ticketView/ticketComments.tsx
import "./ticketComments.less"

import React from 'react'
import CommentView from "./commentView.tsx";
import {TicketDetails} from "../../model/ticketDetails.ts";
import {Comment} from "../../model/comment.ts";

interface TicketCommentsProps {
    ticket : TicketDetails,
}

interface TicketCommentsState {
    ticket : TicketDetails;
    commentText : string;
}

class TicketComments extends React.Component<TicketCommentsProps, TicketCommentsState> {
    constructor(props : TicketCommentsProps) {
        super(props)
        this.state = {
            ticket : this.props.ticket,
            commentText : ""
        }
    }

    addComment(commentText : string) {
        //TicketService.createComment(this.props.ticket, this.state.commentText)

        if(commentText){
            const comment : Comment = {
                id: commentText + Math.round(Math.random() * 100),
                commentText: commentText,
                creationDate: new Date()
            }

            this.setState({commentText: ""})
            this.pushComment(comment)
        }

    }

    pushComment(comment: Comment){
        let newTicket = this.state.ticket;

        newTicket.comments.push(comment)

        this.setState(() => ({ticket: newTicket}))
    }

    addCommentWithEnter(event: any){
        if(event.key === 'Enter'){
            this.addComment(this.state.commentText);
        }
    }

    render() {

        let comments;

        if(this.props.ticket.comments.length == 0){
            comments = <span className="no-comments-info">Noch keine Kommentare eingetragen!</span>;

        }else{
            comments = <div className="comments-list">
                {this.props.ticket.comments.map((comment) =>
                    <CommentView key={comment.id} comment={comment}/>
                )}
            </div>;
        }

        return this.props.ticket.comments && (<div className="comments-container">
            {comments}
            <div className="add-comment-container">
                <input type="text" className="add-comment-input" placeholder="Neuer Kommentar ..." value={this.state.commentText}
                       onKeyUp={(event) => this.addCommentWithEnter(event)}
                       onChange={(input) => {this.setState({commentText: input.target.value}) }}/>
                <button className="fa-solid fa-paper-plane add-comment-icon" onClick={() => this.addComment(this.state.commentText)} />
            </div>
        </div>);
    }
}

export default TicketComments;

// frontend/src/components/ticketView/TicketComments.vue
<template>
    <div class="comments-container" v-if="ticket.comments">
        <span class="no-comments-info" v-if="ticket.comments.length == 0">Noch keine Kommentare eingetragen!</span>
        <div class="comments-list" v-else>
            <CommentView v-for="comment in ticket.comments" :comment="comment"/>
        </div>
        <div class="add-comment-container">
            <input type="text" class="add-comment-input" v-model="commentText" placeholder="Neuer Kommentar ..." @keyup.enter="addComment"/>
            <i class="fa-solid fa-paper-plane add-comment-icon" role="button" @click="addComment"/>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent, type PropType} from "vue";
import type {TicketDetails} from "@/model/ticketDetails";
import CommentView from "@/components/ticketView/CommentView.vue";
import TicketService from "@/services/ticketService";

export default defineComponent({
    name: "TicketComments",
    components: {CommentView},
    props: {
        ticket: {
            type: Object as PropType<TicketDetails>,
            required: true
        }
    },
    data() {
        return {
            commentText: ""
        }
    },
    methods: {
        addComment() {
            TicketService.createComment(this.ticket, this.commentText)
            this.commentText = "";
        }
    }
});
</script>

<style scoped lang="less">
.comments-container {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  max-height: 100%;
  border-radius: 20px;

  .no-comments-info {
    color: var(--basic-light-text-color);
    text-align: center;
    margin: auto;
  }

  .comments-list {
    position: relative;
    height: 1px;
    flex-grow: 1;

    margin-bottom: auto;
    overflow-y: auto;
    display: flex;
    flex-direction: column;

    .comment-container:last-child {
      margin-bottom: 20px;
    }
  }

  .add-comment-container {
    position: relative;

    .add-comment-input {
      width: 100%;
      padding: 20px 70px 20px 20px;
      background: var(--navigation-background-color);
      border-top: 1px solid var(--navigation-border-color);
      outline: none;
    }

    .add-comment-icon {
      position: absolute;
      top: 0;
      right: 0;
      margin: 20px 30px;
      font-size: 1.5em;
      height: 100%;
      line-height: 100%;
      color: var(--basic-dark-text-color);
    }
  }
}
</style>
