// frontend-react/src/components/NavigationBar.tsx
import './NavigationBar.less'
import {Tag} from "../model/tag.ts";
import {useState} from "react";
import TicketServices from "../services/ticketServices.ts";
import TagService from "../services/tagService.ts";
import Modal from "./utils/Modal.tsx";
import TagView from "./TagView.tsx";

function NavigationBar() {
    const tags: Tag[] = []
    const [shouldDisplayTicketModal, setShouldDisplayTicketModal] = useState(false);
    const [shouldDisplayTagModal, setShouldDisplayTagModal] = useState(false);

    const [newTicketName, setNewTicketName] = useState("");

    const createTicket = () => {
        setShouldDisplayTicketModal(false);
        TicketServices.createNewTicketWithName(newTicketName);
    }
    const deleteTag = (id: string) => {
        setShouldDisplayTagModal(false);
        TagService.deleteTag(id);
    }

    return (<>
        <div className="navigation-bar">
            <i className="fa-solid fa-clipboard-list app-icon mr-2"></i>
            <span className="app-title">KanbanQL</span>
            <button className="btn btn-primary ticket-add-button" onClick={() => setShouldDisplayTicketModal(true)}>
                Ticket hinzufügen
            </button>
            <button className="btn btn-primary ticket-add-button" onClick={() => setShouldDisplayTagModal(true)}>
                Tags bearbeiten
            </button>
        </div>
        <Modal saveButtonText="Hinzufügen" onSave={createTicket} showModal={shouldDisplayTicketModal} title="Neues Ticket erstellen">
            <div className="input-group d-flex flex-column">
                <label htmlFor="newTicketName">Name des Tickets:</label>
                <input id="newTicketName"
                       value={newTicketName}
                       onChange={(event) => setNewTicketName(event.target.value)}
                       className="form-control w-100"
                       type="text"
                />
            </div>
        </Modal>
        <Modal saveButtonShow={false}
               cancelButtonText="Fertig"
               showModal={shouldDisplayTagModal}
               title="Tags bearbeiten"
               onCancel={() => setShouldDisplayTagModal(false)}>
            {tags.map((tag) =>
                <div className="tag-line d-flex mb-2" key={tag.id}>
                    <TagView tagId={tag.id}/>
                    <i className="fa-solid fa-trash ml-auto text-center" role="button" onClick={() => deleteTag(tag.id)}/>
                </div>
            )}
        </Modal>
    </>);
}

export default NavigationBar;

// frontend/src/components/NavigationBar.vue
<template>
    <div class="navigation-bar">
        <i class="fa-solid fa-clipboard-list app-icon mr-2"></i>
        <span class="app-title">KanbanQL</span>
        <button class="btn btn-primary ticket-add-button" @click="openCreateTicketModal">Ticket hinzufügen</button>
        <button class="btn btn-primary ticket-add-button" @click="openEditTagsModal">Tags bearbeiten</button>
    </div>
    <Modal ref="addTicketModal" save-button-text="Hinzufügen" @modalSave="createTicket">
        <template v-slot:modal-title>
            Neues Ticket erstellen
        </template>
        <template v-slot:modal-body>
            <div class="input-group d-flex flex-column">
                <label for="newTicketName">Name des Tickets:</label>
                <input id="newTicketName" v-model="newTicketName" class="form-control w-100" type="text"/>
            </div>
        </template>
    </Modal>
    <Modal ref="editTagsModal" :save-button-show="false" cancel-button-text="Fertig">
        <template v-slot:modal-title>
            Tags bearbeiten
        </template>
        <template v-slot:modal-body>
            <div class="tag-line d-flex mb-2" v-for="tag in tags">
                <TagView :tag-id="tag.id"/>
                <i class="fa-solid fa-trash ml-auto text-center" role="button" @click="deleteTag(tag.id)"/>
            </div>
        </template>
    </Modal>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import Modal from "@/components/utils/Modal.vue";
import TicketService from "@/services/ticketService";
import {useTagStore} from "@/stores/tagStore";
import TagView from "@/components/TagView.vue";
import TagService from "@/services/tagService";

export default defineComponent({
    name: "NavigationBar",
    components: {TagView, Modal},
    data() {
        return {
            newTicketName: ""
        }
    },
    setup() {
        const tagStore = useTagStore();

        return {tagStore};
    },
    computed: {
        tags() {
            return this.tagStore.tags;
        }
    },
    methods: {
        openCreateTicketModal() {
            (this.$refs.addTicketModal as typeof Modal).displayModal();
        },
        openEditTagsModal() {
            (this.$refs.editTagsModal as typeof Modal).displayModal();
        },
        createTicket() {
            TicketService.createNewTicketWithName(this.newTicketName);
        },
        deleteTag(id: string) {
            TagService.deleteTag(id);
        }
    }
});
</script>

<style scoped lang="less">
.navigation-bar {
  display: flex;
  width: 100%;
  padding: 10px 20px;
  border-bottom: 1px solid var(--navigation-border-color);
  margin-bottom: 20px;
  background-color: var(--navigation-background-color);

  .app-title {
    text-align: center;
    margin-top: auto;
    margin-bottom: auto;
    font-size: 1.2em;
    padding: 4px 15px 4px 0;

    border-right: 1px solid var(--navigation-border-color);

    line-height: 100%;

    pointer-events: none;
    user-select: none;
  }

  .app-icon {
    text-align: center;
    margin-top: auto;
    margin-bottom: auto;
    font-size: 1.2em;
    border-radius: 10px;

    padding: 10px;
    background: var(--navigation-icon-background-color);

    pointer-events: none;
  }

  .ticket-add-button {
    font-size: 0.9em;
    padding: 5px;
    margin-left: 15px;
  }
}
</style>
