// frontend-react/src/components/ticketBoard/ticketBoard.tsx
import './ticketBoard.less';
import TicketLane from "./ticketLane/ticketLane.tsx";
import {TicketStatus} from "../../enum/ticketStatus.ts";
import {Ticket} from "../../model/ticket.ts";
import TicketServices from "../../services/ticketServices.ts";
import {useState} from "react";

interface TicketBoardProps {
    selectTicket: (ticket: Ticket) => void;
}

export function TicketBoard(props: TicketBoardProps) {
    const [tickets, setTickets] = useState<Array<Ticket>>([])
    TicketServices.fetchAllTickets().then(result =>
        setTickets(result.data.getAllTickets));

    const ticketsByStatus = (status: TicketStatus) => {
        return tickets.filter(ticket => ticket.status.toString() === TicketStatus[status]);
    }

    return <div className="ticket-board">
        <TicketLane
            laneName="Backlog"
            laneColor="gray"
            laneStatus={TicketStatus.BACKLOG}
            tickets={ticketsByStatus(TicketStatus.BACKLOG)}
            selectTicket={(ticket: Ticket) => props.selectTicket(ticket)}
        />
        <TicketLane
            laneName="Geplant"
            laneColor="#C59916"
            laneStatus={TicketStatus.PLANNED}
            tickets={ticketsByStatus(TicketStatus.PLANNED)}
            selectTicket={(ticket: Ticket) => props.selectTicket(ticket)}
        />
        <TicketLane
            laneName="In Arbeit"
            laneColor="#C70039"
            laneStatus={TicketStatus.IN_PROGRESS}
            tickets={ticketsByStatus(TicketStatus.IN_PROGRESS)}
            selectTicket={(ticket: Ticket) => props.selectTicket(ticket)}
        />
        <TicketLane
            laneName="In Review"
            laneColor="#054AD5"
            laneStatus={TicketStatus.TO_REVIEW}
            tickets={ticketsByStatus(TicketStatus.TO_REVIEW)}
            selectTicket={(ticket: Ticket) => props.selectTicket(ticket)}
        />
        <TicketLane
            laneName="Abgeschlossen"
            laneColor="#55AB3C"
            laneStatus={TicketStatus.DONE}
            tickets={ticketsByStatus(TicketStatus.DONE)}
            selectTicket={(ticket: Ticket) => props.selectTicket(ticket)}
        />
    </div>
}

// frontend/src/components/TicketBoard.vue
<template>
    <div class="ticket-board">
        <TicketLane
            lane-name="Backlog"
            :lane-status="TicketStatus.BACKLOG"
            :tickets="ticketsByStatus(TicketStatus.BACKLOG)"
        />
        <TicketLane
            lane-name="Geplant"
            lane-color="#C59916"
            :lane-status="TicketStatus.PLANNED"
            :tickets="ticketsByStatus(TicketStatus.PLANNED)"
        />
        <TicketLane
            lane-name="In Arbeit"
            lane-color="#C70039"
            :lane-status="TicketStatus.IN_PROGRESS"
            :tickets="ticketsByStatus(TicketStatus.IN_PROGRESS)"
        />
        <TicketLane
            lane-name="In Review"
            lane-color="#054AD5"
            :lane-status="TicketStatus.TO_REVIEW"
            :tickets="ticketsByStatus(TicketStatus.TO_REVIEW)"
        />
        <TicketLane
            lane-name="Abgeschlossen"
            lane-color="#55AB3C"
            :lane-status="TicketStatus.DONE"
            :tickets="ticketsByStatus(TicketStatus.DONE)"
        />
    </div>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import {useTicketStore} from "@/stores/ticketStore";
import TicketLane from "@/components/TicketLane.vue";
import type {Ticket} from "@/model/ticket";
import {TicketStatus} from "@/enum/ticketStatus";
import {useTagStore} from "@/stores/tagStore";

export default defineComponent({
    name: "TicketBoard",
    components: {
        TicketLane,
    },
    setup() {
        const ticketStore = useTicketStore();
        const tagStore = useTagStore();
        ticketStore.initialize();
        tagStore.initialize();

        return {ticketStore};
    },
    computed: {
        TicketStatus() {
            return TicketStatus;
        },
        tickets() {
            return this.ticketStore.tickets;
        }
    },
    methods: {
        ticketsByStatus(status: TicketStatus): Array<Ticket> {
            return this.tickets.filter(ticket => ticket.status === status);
        }
    }
});
</script>

<style scoped>
.ticket-board {
    display: flex;
    max-width: 1600px;
    margin-left: auto;
    margin-right: auto;
    flex: 1;
}
</style>
