// frontend/src/components/ticketView/CommentView.vue
<template>
    <div class="comment-container">
        <span class="comment-date">{{ formattedDate }}</span>
        <span class="comment-text">{{ comment.commentText }}</span>
    </div>
</template>

<script lang="ts">
import {defineComponent, type PropType} from "vue";
import type {Comment} from "@/model/comment";

export default defineComponent({
    name: "CommentView",
    props: {
        comment: {
            type: Object as PropType<Comment>,
            required: true
        }
    },
    computed: {
        formattedDate(): string {
            let options = {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
                second: '2-digit'
            } as Intl.DateTimeFormatOptions;

            return this.comment.creationDate.toLocaleDateString("de-DE", options);
        }
    }
});
</script>

<style scoped lang="less">
.comment-container {
  display: flex;
  flex-direction: column;

  .comment-date {
    margin: 10px 25px 0 25px;
    font-weight: 300;
    font-size: 0.8em;
  }

  .comment-text {
    background-color: var(--navigation-background-color);
    width: calc(100% - 50px);
    border: 1px solid var(--navigation-border-color);
    border-radius: 10px;
    margin: 0 20px 0 20px;
    padding: 5px;
  }
}
</style>

// frontend-react/src/components/ticketView/ticketSecondaryColumn/ticketComments/commentView/commentView.tsx
import "./commentView.less"
import React from 'react'
import {Comment} from "../../../../../model/comment.ts";

interface CommentViewProps {
    comment : Comment
}

interface CommentViewState {

}

class CommentView extends React.Component<CommentViewProps, CommentViewState> {
    state : CommentViewState = {   }
    formattedDate(): string {
        let options = {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
        } as Intl.DateTimeFormatOptions;

        return this.props.comment.creationDate.toLocaleDateString("de-DE", options);
    }
    render() {
        return <div className="comment-container">
            <span className="comment-date">{ this.formattedDate() }</span>
            <span className="comment-text">{ this.props.comment.commentText }</span>
        </div>;
    }

}

export default CommentView;
