// frontend/src/components/ticketView/TicketStatusBar.vue
<template>
    <div class="ticket-status-bar" v-if="ticket">
        <StatusSelector :status="ticket.status" class="mr-3" @Change-status="selectStatus"/>
        <hr style="rotate: 90deg;width: 1.5em"/>
        <PrioritySelector
            class="ml-3"
            :current-priority="ticket.priority"
            @selectPriority="selectPriority"/>
        <i class="fa-solid fa-trash" @click="deleteTicket" role="button"/>
    </div>
</template>

<script lang="ts">
import type {Priority} from "@/enum/priority";
import type {PropType} from "vue";
import {defineComponent} from "vue";
import PrioritySelector from "@/components/PrioritySelector.vue";
import StatusSelector from "@/components/ticketView/StatusSelector.vue";
import type {TicketDetails} from "@/model/ticketDetails";
import TicketService from "@/services/ticketService";
import type {TicketStatus} from "@/enum/ticketStatus";

export default defineComponent({
    name: "TicketStatusBar",
    components: {StatusSelector, PrioritySelector},
    props: {
        ticket: {
            type: Object as PropType<TicketDetails>,
            required: true
        }
    },
    emits: ["selectPriority", "CloseTicketView"],
    methods: {
        selectPriority(priority: Priority) {
            TicketService.updatePriority(this.ticket.id, priority, this.ticket);
        },
        selectStatus(status: TicketStatus) {
            TicketService.updateStatus(this.ticket.id, status, this.ticket);
        },
        deleteTicket() {
            TicketService.deleteTicket(this.ticket.id);
            this.$emit("CloseTicketView");
        }
    }
});
</script>

<style scoped lang="less">
.ticket-status-bar {
    width: 100%;
    padding: 20px;
    height: 80px;
    border-bottom: 1px solid var(--navigation-border-color);
    display: flex;
    align-items: center;
}
</style>

// frontend-react/src/components/ticketView/ticketStatusBar.tsx
import "./ticketStatusBar.less"
import React from 'react'
import StatusSelector from "./statusSelector.tsx";
import {TicketDetails} from "../../model/ticketDetails.ts";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faTrash} from "@fortawesome/free-solid-svg-icons/faTrash";
import {Priority} from "../../enum/priority.ts";
import {TicketStatus} from "../../enum/ticketStatus.ts";
//import TicketService from "../../services/ticketServices.ts"
import PrioritySelector from "../PrioritySelector.tsx";

interface TicketStatusBarProps {
    ticket : TicketDetails;
    OnTicketViewClosed : () => void;
}

interface TicketStatusBarState {
    ticket : TicketDetails
}

class TicketStatusBar extends React.Component<TicketStatusBarProps, TicketStatusBarState> {
    constructor(props : TicketStatusBarProps) {
        super(props)
        this.state = {
            ticket : this.props.ticket
        }
    }

    selectPriority(priority: Priority) {
        this.setState((prevState) => {
            prevState.ticket.priority = priority;
            return ({ticket: prevState.ticket});
        })
        //TicketService.updatePriority(this.props.ticket.id, priority, this.props.ticket);
    }
    selectStatus(status: TicketStatus) {
        this.setState((prevState) => {
            prevState.ticket.status = status;
            return ({ticket: prevState.ticket});
        })
        //TicketService.updateStatus(this.props.ticket.id, status, this.props.ticket);
    }
    deleteTicket() {
        this.props.OnTicketViewClosed()
        //TicketService.deleteTicket(this.props.ticket.id);
    }
    render() {
        return this.state.ticket && <div className="ticket-status-bar">
            <StatusSelector status={this.state.ticket.status}  className="mr-3" changeStatus={(status) => this.selectStatus(status)}/>
            <hr style={{rotate: "90deg", width: "1.5em", margin:0 }}/>
            <PrioritySelector currentPriority={this.state.ticket.priority} className="ml-3" selectPriority={(priority) => this.selectPriority(priority)}/>
            <FontAwesomeIcon icon={faTrash} className="fa-solid fa-trash" onClick={() => {this.deleteTicket();}}/>

        </div>;
    }

}

export default TicketStatusBar;
