// frontend/src/components/ticketView/TicketView.vue
<template>
    <div class="ticket-view">
        <BackgroundBlocker background-color="rgba(50, 50, 50, 0.4)"/>
        <div class="ticket-view-main">
            <TicketViewHeader/>
            <div class="ticket-column-container d-flex flex-row flex-grow-1">
                <TicketMainColumn/>
                <TicketSecondaryColumn/>
            </div>
        </div>
    </div>
</template>

<script lang="ts">

import {defineComponent} from "vue";
import BackgroundBlocker from "@/components/utils/BackgroundBlocker.vue";
import TicketViewHeader from "@/components/ticketView/TicketViewHeader.vue";
import TicketMainColumn from "@/components/ticketView/TicketMainColumn.vue";
import TicketSecondaryColumn from "@/components/ticketView/TicketSecondaryColumn.vue";

export default defineComponent({
    name: "TicketView",
    components: {TicketSecondaryColumn, TicketMainColumn, BackgroundBlocker, TicketViewHeader}
})
</script>

<style scoped lang="less">
.ticket-view {
  position: fixed;
  width: 100vw;
  height: 100vh;
  top: 0;
  left: 0;
  display: flex;

  .ticket-view-main {
    position: relative;
    z-index: 150;
    display: flex;
    flex-direction: column;

    margin: auto;
    max-width: 1600px;
    width: 100%;
    height: 90%;
    background: white;
    border-radius: 20px;
    box-shadow: var(--main-view-box-shadow-color) 0 2px 6px;
  }
}
</style>

// frontend-react/src/components/ticketView/ticketView.tsx
import "./ticketView.less"
import BackgroundBlocker from "../utils/BackgroundBlocker.tsx";
import TicketViewHeader from "./ticketViewHeader/ticketViewHeader.tsx";
import TicketMainColumn from "./ticketMainColumn/ticketMainColumn.tsx";
import TicketSecondaryColumn from "./ticketSecondaryColumn/ticketSecondaryColumn.tsx";
import {TicketDetails} from "../../model/ticketDetails.ts";

interface TicketViewProps {
    ticket: TicketDetails
    onTicketViewClosed: () => void;
}

function TicketView(props: TicketViewProps) {
    return <div className="ticket-view">
        <BackgroundBlocker backgroundColor="rgba(50, 50, 50, 0.4)" customZIndex={25} onClick={props.onTicketViewClosed}/>

        <div className="ticket-view-main">
            <TicketViewHeader onTicketViewClosed={props.onTicketViewClosed}/>
            <div className="ticket-column-container d-flex flex-row flex-grow-1">
                <TicketMainColumn ticket={props.ticket} onTicketViewClosed={props.onTicketViewClosed}/>
                <TicketSecondaryColumn ticket={props.ticket}/>
            </div>
        </div>
    </div>;
}

export default TicketView;
