// frontend/src/components/ticketView/TicketMainColumn.vue
<template>
    <div class="main-column-container">
        <TicketStatusBar :ticket="ticket" @CloseTicketView="closeTicketView"/>
        <div class="main-column">
            <input type="text" id="name-field" v-model="newTitle" class="ticket-name-input" @focusout="saveNewTitle"/>
            <textarea type="text" id="name-field" v-model="newDescription" class="ticket-description-input"
                      placeholder="Geben Sie hier eine Beschreibung ein..." @focusout="saveNewDescription"/>
        </div>
    </div>
</template>

<script lang="ts">
import {defineComponent, type PropType} from "vue";
import TicketStatusBar from "@/components/ticketView/TicketStatusBar.vue";
import type {TicketDetails} from "@/model/ticketDetails";
import TicketService from "@/services/ticketService";

export default defineComponent({
    name: "TicketMainColumn",
    components: {TicketStatusBar},
    emits: ["CloseTicketView"],
    props: {
        ticket: {
            type: Object as PropType<TicketDetails>,
            required: true
        }
    },
    data() {
        return {
            newTitle: "",
            newDescription: ""
        }
    },
    mounted() {
        this.newTitle = this.ticket.title;
        this.newDescription = this.ticket.description;
    },
    methods: {
        closeTicketView() {
            this.$emit("CloseTicketView");
        },
        saveNewTitle() {
            if (this.newTitle === "") {
                this.newTitle = this.ticket.title;
                return;
            }

            TicketService.updateTitle(this.ticket.id, this.newTitle, this.ticket);
        },
        saveNewDescription() {
            TicketService.updateDescription(this.ticket.id, this.newDescription, this.ticket);
        }
    }
});
</script>

<style scoped lang="less">
.main-column-container {
    width: 60%;
    border-right: 1px solid var(--navigation-border-color);
    display: flex;
    flex-direction: column;

    .main-column {
        display: flex;
        flex-direction: column;
        padding: 30px;
        flex-grow: 1;

        .ticket-name-input {
            padding: 11px;
            width: 100%;
            border: none;
            outline: none;
            font-size: 1.5em;
            margin-bottom: 30px;

            &:hover, &:focus {
                padding: 10px;
                border: 1px dashed var(--navigation-border-color);
            }
        }

        .ticket-description-input {
            padding: 21px;
            width: 100%;
            flex-grow: 1;
            border: none;
            outline: none;
            margin-bottom: 30px;
            resize: none;

            &:hover, &:focus {
                padding: 20px;
                border: 1px dashed var(--navigation-border-color);
            }
        }
    }
}
</style>

// frontend-react/src/components/ticketView/ticketMainColumn.tsx
import "./ticketMainColumn.less"
import React from 'react'
import TicketStatusBar from "./ticketStatusBar.tsx";
import {TicketDetails} from "../../model/ticketDetails.ts";

interface TicketMainColumnProps {
    ticket : TicketDetails;
    onTicketViewClosed : () => void;
}

interface TicketMainColumnState {
    ticket: TicketDetails
    title : string;
    description : string
}

class TicketMainColumn extends React.Component<TicketMainColumnProps, TicketMainColumnState> {
    constructor(props : TicketMainColumnProps) {
        super(props)
        this.state = {
            ticket : props.ticket,
            title : props.ticket.title,
            description : props.ticket.description
        }
    }

    saveNewTitle(newTitle : string) {
        if (newTitle === "") {
            this.setState((prevState) => ({title: prevState.title}));
            return;
        }
        let newTicket = this.state.ticket;

        newTicket.title = newTitle;

        this.setState({title: newTitle});
        this.setState(() => ({ticket: newTicket}));


        //TicketService.updateTitle(this.ticket.id, this.newTitle, this.ticket);
    }
    saveNewDescription(newDescription : string) {
        if (newDescription === "") {
            this.setState((prevState) => ({description: prevState.description}));
            return;
        }
        let newTicket = this.state.ticket;

        newTicket.description = newDescription;

        this.setState({description: newDescription});
        this.setState(() => ({ticket: newTicket}));
        //TicketService.updateDescription(this.ticket.id, this.newDescription, this.ticket);
    }

    render() {
        return <div className="main-column-container">
            <TicketStatusBar ticket={this.props.ticket} OnTicketViewClosed={this.props.onTicketViewClosed} />
            <div className="main-column">
                <input type="text" id="name-field" value={this.state.title} onChange={(input) => {this.setState({title: input.target.value}) }}
                       className="ticket-name-input"  onBlur={(event) => this.saveNewTitle(event.target.value)}/>
                <textarea  id="name-field" value={this.state.description} className="ticket-description-input" onChange={(input) => {this.setState({description: input.target.value}) }}
                          placeholder="Geben Sie hier eine Beschreibung ein..." onBlur={(event) => this.saveNewDescription(event.target.value)}/>
            </div>
        </div>;
    }

}

export default TicketMainColumn;
